/*
 * 펫 목록 — 원본 폴더(assets/pixel_pets_png/pixel_pets/1x/characters/{free,premium})에서 만든다.
 *
 * 맨 아래 "자동 생성" 블록은 scripts/build-pet-assets.mjs가 원본 파일 이름으로 다시 쓴다
 * (손으로 고치지 말 것). 이름·채굴력 규칙은 이 파일 위쪽에서 정한다.
 * 가격은 features/shop/domain/shopItems.ts, 수치와 이유는 daon-content/재화_경제.md.
 *
 * 앱과 서버(Deno)가 같이 불러오므로 다른 파일을 import하지 않는다.
 */

export type PetCurrency = 'coin' | 'prism';

export interface PetDef {
  /** 'cat_orange'처럼 종_색 — 원본·앱 이미지 파일 이름과 같다 */
  id: string;
  species: string;
  color: string;
  /** 프리미엄 폴더 펫 = 프리즘으로 산다 */
  currency: PetCurrency;
  /** 출석 채굴력 — 코인 펫 1, 프리즘 펫 3 */
  power: number;
  /** 화면 이름 (예: '치즈 고양이') */
  label: string;
}

export const SPECIES_LABEL: Record<string, string> = {
  bunny: '토끼',
  cat: '고양이',
  dog: '강아지',
  fox: '여우',
  frog: '개구리',
  ghost: '유령',
  hamster: '햄스터',
  hedgehog: '고슴도치',
  mole: '두더지',
  mushroom: '버섯',
  penguin: '펭귄',
  robot: '로봇',
  slime: '슬라임',
  dragon: '드래곤',
  golem: '골렘',
  mimic: '미믹',
};

const COLOR_LABEL: Record<string, string> = {
  // 코인 펫
  arctic: '북극',
  black: '검정',
  blue: '파랑',
  brown: '갈색',
  choco: '초코',
  cream: '크림',
  golden: '황금',
  gray: '회색',
  green: '초록',
  lime: '라임',
  lavender: '라벤더',
  mint: '민트',
  navy: '남색',
  orange: '주황',
  panda: '판다',
  pink: '분홍',
  purple: '보라',
  red: '빨강',
  rust: '적갈',
  sand: '모래',
  silver: '은빛',
  sky: '하늘',
  spotted: '얼룩',
  teal: '청록',
  white: '하양',
  yellow: '노랑',
  // 프리즘 펫
  amethyst: '자수정',
  aurora: '오로라',
  classic: '클래식',
  crystal: '수정',
  diamond: '다이아',
  ember: '불꽃',
  firefly: '반딧불',
  frost: '서리',
  galaxy: '은하',
  glow: '빛나는',
  hacker: '해커',
  kitsune: '구미호',
  lava: '용암',
  neon: '네온',
  obsidian: '흑요석',
  rainbow: '무지개',
  royal: '로열',
  ruby: '루비',
  sakura: '벚꽃',
};

/** 이름이 따로 있는 펫 */
const LABEL_OVERRIDE: Record<string, string> = {
  cat_orange: '치즈 고양이',
};

/** 처음부터 가진 펫 (0008_pets.sql의 기본값과 같아야 한다) */
export const DEFAULT_PET_ID = 'cat_orange';

/** 원본 폴더 이름(free/premium) → 재화·채굴력 */
function define(id: string, premium: boolean): PetDef {
  const [species, color] = id.split('_');
  return {
    id,
    species,
    color,
    currency: premium ? 'prism' : 'coin',
    power: premium ? 3 : 1,
    label:
      LABEL_OVERRIDE[id] ?? `${COLOR_LABEL[color] ?? color} ${SPECIES_LABEL[species] ?? species}`,
  };
}

// <generated by scripts/build-pet-assets.mjs — 손으로 고치지 말 것>
const FREE_IDS: string[] = [
  'bunny_choco',
  'bunny_cream',
  'bunny_gray',
  'bunny_pink',
  'bunny_sky',
  'bunny_spotted',
  'bunny_white',
  'cat_blue',
  'cat_cream',
  'cat_gray',
  'cat_mint',
  'cat_orange',
  'cat_pink',
  'cat_white',
  'dog_brown',
  'dog_choco',
  'dog_cream',
  'dog_golden',
  'dog_gray',
  'dog_spotted',
  'dog_white',
  'fox_arctic',
  'fox_black',
  'fox_brown',
  'fox_cream',
  'fox_orange',
  'fox_red',
  'fox_silver',
  'frog_blue',
  'frog_brown',
  'frog_green',
  'frog_lime',
  'frog_pink',
  'frog_teal',
  'frog_yellow',
  'ghost_gray',
  'ghost_lavender',
  'ghost_mint',
  'ghost_pink',
  'ghost_sky',
  'ghost_white',
  'ghost_yellow',
  'hamster_black',
  'hamster_brown',
  'hamster_cream',
  'hamster_golden',
  'hamster_gray',
  'hamster_panda',
  'hamster_white',
  'hedgehog_blue',
  'hedgehog_brown',
  'hedgehog_choco',
  'hedgehog_cream',
  'hedgehog_gray',
  'hedgehog_pink',
  'hedgehog_white',
  'mole_black',
  'mole_brown',
  'mole_choco',
  'mole_cream',
  'mole_gray',
  'mole_rust',
  'mole_sand',
  'mushroom_blue',
  'mushroom_brown',
  'mushroom_green',
  'mushroom_pink',
  'mushroom_purple',
  'mushroom_red',
  'mushroom_yellow',
  'penguin_black',
  'penguin_blue',
  'penguin_brown',
  'penguin_gray',
  'penguin_mint',
  'penguin_navy',
  'penguin_pink',
  'robot_black',
  'robot_blue',
  'robot_green',
  'robot_orange',
  'robot_red',
  'robot_silver',
  'robot_white',
  'slime_blue',
  'slime_green',
  'slime_mint',
  'slime_orange',
  'slime_pink',
  'slime_purple',
  'slime_yellow',
];
const PREMIUM_IDS: string[] = [
  'bunny_sakura',
  'cat_rainbow',
  'dog_galaxy',
  'dragon_aurora',
  'dragon_ember',
  'dragon_obsidian',
  'fox_kitsune',
  'frog_firefly',
  'ghost_neon',
  'golem_amethyst',
  'golem_diamond',
  'golem_ruby',
  'hamster_rainbow',
  'hedgehog_crystal',
  'mimic_classic',
  'mimic_frost',
  'mimic_royal',
  'mole_diamond',
  'mushroom_glow',
  'penguin_aurora',
  'robot_hacker',
  'slime_lava',
];
// </generated>

/** 전체 펫 — 프리즘 펫이 먼저, 그다음 코인 펫 (종·색 이름순) */
export const PETS: PetDef[] = [
  ...PREMIUM_IDS.map((id) => define(id, true)),
  ...FREE_IDS.map((id) => define(id, false)),
];

const BY_ID = new Map(PETS.map((p) => [p.id, p]));

export function petById(id: string): PetDef | undefined {
  return BY_ID.get(id);
}

/** 펫별 채굴력 표 — 서버가 DB 함수(check_in)에 그대로 넘긴다 */
export const PET_POWER: Record<string, number> = Object.fromEntries(
  PETS.map((p) => [p.id, p.power])
);

/** 팀 채굴력 합 — 시간당 게이지를 정한다 (mining.ts의 pointsPerHour) */
export function miningPower(team: string[]): number {
  return team.reduce((sum, id) => sum + (petById(id)?.power ?? 1), 0);
}
